#FL Settings
fl:
  num_rounds: 2
  num_clients: 100
  batch_size: 20

#Client settings - what server tell each client to use in their local training
client:
  lr: 0.1 #learning rate
  momentum: 0.9
  local_epochs: 1
  num_classes: 10 #MNIST data has 10 classes
  num_clients_per_round_fit: 5
  num_clients_per_round_evaluate: 10 #After each round if we have 100 clients 1/4 will be used to evaluate what's characteristic of the global model

#Dataset selection
dataset:
  name: mnist  # Change to "cifar10" to switch dataset

# Dataset-specific configs
datasets:
  mnist:
    path: ./data/mnist
    input_size: 28
    channels: 1
    num_classes: 10
    batch_size: 32
  cifar10:
    path: ./data/cifar10
    input_size: 32
    channels: 3
    num_classes: 10
    batch_size: 64

#SNN MODELS
model:
  name: snn_model1

#SNN-specific configs
snn_method1:
  hidden_size: 128
  spike_threshold: 1.0
  time_steps: 20
  learning_rate: 0.001
  optimizer: adam

snn_method2:
  input_dim: 1024
  membrane_decay: 0.25
  tau: 10
  learning_rate: 0.0005
  optimizer: sgd