---
_target_: biograd.network_w_biograd.BioGradNetworkWithSleep

input_dim: 2312
output_dim: ${client.num_classes}
hidden_dim_list: [500, 100]
param_dict:
  hidden_layer:
    - [0.3, 0.3, 0.3, 1.0]
    - [0.3, 0.3, 0.3, 1.0]
  out_layer: [0.3, 0.3, 0.3, 1.0]

device: cuda
error_func: null