# It's good practice to rename the file/model to reflect the dataset
_target_: SNN_Models.Spide.SNNSPIDEConvNet
cfg:
  # This 'MODEL' key matches the structure expected by your parse_cfg method
  MODEL:
    # --- Core Input Shape Changes (Correct in your example) ---
    c_in: 2          # CORRECT: N-MNIST uses 2 channels for ON/OFF event polarities.
    h_hidden: 34     # CORRECT: N-MNIST standard spatial dimension is 34.
    w_hidden: 34     # CORRECT: N-MNIST standard spatial dimension is 34.

    # --- Architectural Hyperparameters (May need tuning) ---
    c_hidden: 15     # This is a hyperparameter. The value is likely fine to start.
    c_s1: 40         # This is a hyperparameter. The value is likely fine to start.
    fc_num: 300      # This is a hyperparameter. The value is likely fine to start.
    num_classes: 10  # This will be loaded from elsewhere, correct for N-MNIST.
    kernel_size_x: 5
    stride_x: 1
    padding_x: 2     # With these settings, a 34x34 input gives a 34x34 output from this layer.
    kernel_size_s: 5
    dropout: 0.5     # Increased dropout as N-MNIST can be more complex. Good to tune.

    # --- SNN-Specific Hyperparameters (CRITICAL FOR N-MNIST) ---
    # These are the most important values to experiment with.
    # N-MNIST's sparse, event-based data behaves very differently from dense MNIST frames.
    time_step: 20    # SUGGESTION: N-MNIST often benefits from longer simulation times
    time_step_back: 10 # A good starting point could be half of time_step.
    vth: 0.2    
    vth_back: 0.2
    u_rest: 0.0     
    u_rest_back: 0.0
    leaky: 0.9       